export const projects = [
  {
    slug: 'parterowy-1',
    name: 'Parterowy 1',
    price: 535000,
    hasGarage: true,
    available: true,
    description:
      'Nowoczesny dom parterowy, zaprojektowany w nowoczesnej technologii. Prosta bryła domu dzięki ciekawie dobranej elewacji prezentuje się bardzo efektownie. Jest to dom idealny dla 4-5 osobowej rodziny. W domu znajduje się otwarta, przestronna kuchnia z jadalnią oraz salon z wyjściem na taras. Zaprojektowano trzy sypialnie oraz 2 łazienki, pomieszczenie gospodarcze/kotłownia oraz garaż.',
    zones:
      'Reprezentacyjna oraz nocna są wyraźnie wydzielone, co zapewnia domownikom wygodę i komfort użytkowania. Pomieszczenia zaprojektowane zostały z myślą o maksymalnej funkcjonalności - wnętrza będą ustawne, przestronne i jasne.',
    general: {
      buildingArea: '161.17 m²',
      usableArea: '127.40 m²',
      volume: '552.81 m³',
      roofAngle: '2°',
      rooms: 3,
      type: 'murowany',
    },
    plotDimensions: { width: '22.61 m', length: '27.78 m' },
    rooms: [
      { name: 'Pokój dzienny', area: '31.45 m²' },
      { name: 'Kuchnia', area: '10.85 m²' },
      { name: 'Sypialnia I', area: '10.85 m²' },
      { name: 'Sypialnia II', area: '12.70 m²' },
      { name: 'Sypialnia III', area: '9.15 m²' },
      { name: 'Łazienka', area: '4.70 m²' },
      { name: 'WC', area: '2.15 m²' },
      { name: 'Przedsionek/pom. techniczne', area: '3.00 m²' },
      { name: 'Komunikacja', area: '10.50 m²' },
      { name: 'Kotłownia', area: '5.40 m²' },
      { name: 'Garaż', area: '26.65 m²' },
    ],
    construction: [
      { name: 'Fundamenty', value: 'płyta fundamentowa' },
      { name: 'Ściany', value: 'pustak ceramiczny' },
      { name: 'Strop', value: 'drewniany' },
      {
        name: 'Dach',
        value:
          'izolacja pozioma polistyren ekstrudowany EPS oraz membrana dachowa',
      },
      { name: 'Okna', value: 'PCV trzyszybowe' },
      {
        name: 'Stolarka drzwiowa',
        value: 'drzwi zewnętrzne i stalowe do pom. gosp. + brama garażowa',
      },
      { name: 'Tynki', value: 'gipsowe' },
      { name: 'Posadzki', value: 'betonowe' },
      {
        name: 'Instalacje',
        value: 'ogrzewanie podłogowe, instalacje elektryczne i wod.-kan.',
      },
      { name: 'Elewacja', value: 'styropian i tynk silikonowy' },
    ],
    images: [
      '/images/parterowy1/1.jpg',
      '/images/parterowy1/2.jpg',
      '/images/parterowy1/3.jpg',
      '/images/parterowy1/4.jpg',
    ],
    floorPlan: '/images/parterowy1/rzut.jpg',
    sitePlan: '/images/parterowy1/sytuacja.jpg',
    kulaUrl:
      'https://kuula.co/share/hxTT1/collection/7DJXn?logo=0&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&enablejs=1&fid=0f44&priority=1',
  },
  {
    slug: 'parterowy-4',
    name: 'Parterowy 4',
    price: 559000,
    hasGarage: true,
    available: true,
    description:
      'Przestronny dom parterowy z garażem. Największy projekt w ofercie, idealny dla większej rodziny szukającej komfortu i przestrzeni.',
    zones:
      'Reprezentacyjna oraz nocna są wyraźnie wydzielone, co zapewnia domownikom wygodę i komfort użytkowania.',
    general: {
      buildingArea: '177.00 m²',
      usableArea: '141.10 m²',
      volume: '610.00 m³',
      roofAngle: '2°',
      rooms: 4,
      type: 'murowany',
    },
    plotDimensions: { width: '24.00 m', length: '30.00 m' },
    rooms: [
      { name: 'Pokój dzienny', area: '35.00 m²' },
      { name: 'Kuchnia', area: '12.00 m²' },
      { name: 'Sypialnia I', area: '14.00 m²' },
      { name: 'Sypialnia II', area: '13.00 m²' },
      { name: 'Sypialnia III', area: '11.00 m²' },
      { name: 'Sypialnia IV', area: '10.00 m²' },
      { name: 'Łazienka', area: '5.00 m²' },
      { name: 'WC', area: '2.50 m²' },
      { name: 'Komunikacja', area: '12.00 m²' },
      { name: 'Kotłownia', area: '5.00 m²' },
      { name: 'Garaż', area: '28.00 m²' },
    ],
    construction: [
      { name: 'Fundamenty', value: 'płyta fundamentowa' },
      { name: 'Ściany', value: 'pustak ceramiczny' },
      { name: 'Strop', value: 'drewniany' },
      {
        name: 'Dach',
        value:
          'izolacja pozioma polistyren ekstrudowany EPS oraz membrana dachowa',
      },
      { name: 'Okna', value: 'PCV trzyszybowe' },
      {
        name: 'Stolarka drzwiowa',
        value: 'drzwi zewnętrzne i stalowe do pom. gosp. + brama garażowa',
      },
      { name: 'Tynki', value: 'gipsowe' },
      { name: 'Posadzki', value: 'betonowe' },
      {
        name: 'Instalacje',
        value: 'ogrzewanie podłogowe, instalacje elektryczne i wod.-kan.',
      },
      { name: 'Elewacja', value: 'styropian i tynk silikonowy' },
    ],
    images: [
      '/images/parterowy4/1.jpg',
      '/images/parterowy4/2.jpg',
      '/images/parterowy4/3.jpg',
      '/images/parterowy4/4.jpg',
    ],
    floorPlan: '/images/parterowy4/rzut.jpg',
    sitePlan: '/images/parterowy4/sytuacja.jpg',
    kulaUrl:
      'https://kuula.co/share/hxTT1/collection/7DJXn?logo=0&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&enablejs=1&fid=0f44&priority=1',
  },
  {
    slug: 'parterowy-7',
    name: 'Parterowy 7',
    price: 529000,
    hasGarage: true,
    available: true,
    description:
      'Kompaktowy dom parterowy z garażem w atrakcyjnej cenie. Funkcjonalny układ, trzy sypialnie i taras od strony ogrodu.',
    zones:
      'Reprezentacyjna oraz nocna są wyraźnie wydzielone, co zapewnia domownikom wygodę i komfort użytkowania.',
    general: {
      buildingArea: '135.00 m²',
      usableArea: '104.75 m²',
      volume: '450.00 m³',
      roofAngle: '2°',
      rooms: 3,
      type: 'murowany',
    },
    plotDimensions: { width: '20.00 m', length: '25.00 m' },
    rooms: [
      { name: 'Pokój dzienny', area: '28.00 m²' },
      { name: 'Kuchnia', area: '10.00 m²' },
      { name: 'Sypialnia I', area: '12.00 m²' },
      { name: 'Sypialnia II', area: '11.00 m²' },
      { name: 'Sypialnia III', area: '9.00 m²' },
      { name: 'Łazienka', area: '4.50 m²' },
      { name: 'WC', area: '2.00 m²' },
      { name: 'Komunikacja', area: '8.00 m²' },
      { name: 'Kotłownia', area: '4.25 m²' },
      { name: 'Garaż', area: '24.00 m²' },
    ],
    construction: [
      { name: 'Fundamenty', value: 'płyta fundamentowa' },
      { name: 'Ściany', value: 'pustak ceramiczny' },
      { name: 'Strop', value: 'drewniany' },
      {
        name: 'Dach',
        value:
          'izolacja pozioma polistyren ekstrudowany EPS oraz membrana dachowa',
      },
      { name: 'Okna', value: 'PCV trzyszybowe' },
      {
        name: 'Stolarka drzwiowa',
        value: 'drzwi zewnętrzne i stalowe do pom. gosp. + brama garażowa',
      },
      { name: 'Tynki', value: 'gipsowe' },
      { name: 'Posadzki', value: 'betonowe' },
      {
        name: 'Instalacje',
        value: 'ogrzewanie podłogowe, instalacje elektryczne i wod.-kan.',
      },
      { name: 'Elewacja', value: 'styropian i tynk silikonowy' },
    ],
    images: [
      '/images/parterowy7/1.jpg',
      '/images/parterowy7/2.jpg',
      '/images/parterowy7/3.jpg',
      '/images/parterowy7/4.jpg',
    ],
    floorPlan: '/images/parterowy7/rzut.jpg',
    sitePlan: '/images/parterowy7/sytuacja.jpg',
    kulaUrl:
      'https://kuula.co/share/hxTT1/collection/7DJXn?logo=0&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&enablejs=1&fid=0f44&priority=1',
  },
  {
    slug: 'parterowy-2',
    name: 'Parterowy 2',
    price: 529000,
    hasGarage: false,
    available: true,
    description:
      'Przytulny dom parterowy bez garażu. Trzy sypialnie, przestronny salon i wyjście na ogród. Idealne dla par i małych rodzin.',
    zones:
      'Reprezentacyjna oraz nocna są wyraźnie wydzielone, co zapewnia domownikom wygodę i komfort użytkowania.',
    general: {
      buildingArea: '120.00 m²',
      usableArea: '96.70 m²',
      volume: '410.00 m³',
      roofAngle: '2°',
      rooms: 3,
      type: 'murowany',
    },
    plotDimensions: { width: '18.00 m', length: '24.00 m' },
    rooms: [
      { name: 'Pokój dzienny', area: '28.00 m²' },
      { name: 'Kuchnia', area: '10.00 m²' },
      { name: 'Sypialnia I', area: '12.00 m²' },
      { name: 'Sypialnia II', area: '11.00 m²' },
      { name: 'Sypialnia III', area: '9.00 m²' },
      { name: 'Łazienka', area: '4.50 m²' },
      { name: 'WC', area: '2.00 m²' },
      { name: 'Komunikacja', area: '8.00 m²' },
      { name: 'Kotłownia', area: '5.20 m²' },
    ],
    construction: [
      { name: 'Fundamenty', value: 'płyta fundamentowa' },
      { name: 'Ściany', value: 'pustak ceramiczny' },
      { name: 'Strop', value: 'drewniany' },
      {
        name: 'Dach',
        value:
          'izolacja pozioma polistyren ekstrudowany EPS oraz membrana dachowa',
      },
      { name: 'Okna', value: 'PCV trzyszybowe' },
      { name: 'Stolarka drzwiowa', value: 'drzwi zewnętrzne' },
      { name: 'Tynki', value: 'gipsowe' },
      { name: 'Posadzki', value: 'betonowe' },
      {
        name: 'Instalacje',
        value: 'ogrzewanie podłogowe, instalacje elektryczne i wod.-kan.',
      },
      { name: 'Elewacja', value: 'styropian i tynk silikonowy' },
    ],
    images: [
      '/images/parterowy2/1.jpg',
      '/images/parterowy2/2.jpg',
      '/images/parterowy2/3.jpg',
      '/images/parterowy2/4.jpg',
    ],
    floorPlan: '/images/parterowy2/rzut.jpg',
    sitePlan: '/images/parterowy2/sytuacja.jpg',
    kulaUrl:
      'https://kuula.co/share/hxTT1/collection/7DJXn?logo=0&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&enablejs=1&fid=0f44&priority=1',
  },
  {
    slug: 'parterowy-3',
    name: 'Parterowy 3',
    price: 475000,
    hasGarage: false,
    available: true,
    description:
      'Najmniejszy i najbardziej ekonomiczny projekt w ofercie. Dwie sypialnie, salon i taras. Doskonały wybór na start lub dla seniorów ceniących wygodę i brak schodów.',
    zones:
      'Reprezentacyjna oraz nocna są wyraźnie wydzielone, co zapewnia domownikom wygodę i komfort użytkowania.',
    general: {
      buildingArea: '105.00 m²',
      usableArea: '85.50 m²',
      volume: '360.00 m³',
      roofAngle: '2°',
      rooms: 2,
      type: 'murowany',
    },
    plotDimensions: { width: '16.00 m', length: '22.00 m' },
    rooms: [
      { name: 'Pokój dzienny', area: '25.00 m²' },
      { name: 'Kuchnia', area: '9.00 m²' },
      { name: 'Sypialnia I', area: '12.00 m²' },
      { name: 'Sypialnia II', area: '10.00 m²' },
      { name: 'Łazienka', area: '4.50 m²' },
      { name: 'WC', area: '2.00 m²' },
      { name: 'Komunikacja', area: '7.00 m²' },
      { name: 'Kotłownia', area: '5.00 m²' },
    ],
    construction: [
      { name: 'Fundamenty', value: 'płyta fundamentowa' },
      { name: 'Ściany', value: 'pustak ceramiczny' },
      { name: 'Strop', value: 'drewniany' },
      {
        name: 'Dach',
        value:
          'izolacja pozioma polistyren ekstrudowany EPS oraz membrana dachowa',
      },
      { name: 'Okna', value: 'PCV trzyszybowe' },
      { name: 'Stolarka drzwiowa', value: 'drzwi zewnętrzne' },
      { name: 'Tynki', value: 'gipsowe' },
      { name: 'Posadzki', value: 'betonowe' },
      {
        name: 'Instalacje',
        value: 'ogrzewanie podłogowe, instalacje elektryczne i wod.-kan.',
      },
      { name: 'Elewacja', value: 'styropian i tynk silikonowy' },
    ],
    images: [
      '/images/parterowy3/1.jpg',
      '/images/parterowy3/2.jpg',
      '/images/parterowy3/3.jpg',
      '/images/parterowy3/4.jpg',
    ],
    floorPlan: '/images/parterowy3/rzut.jpg',
    sitePlan: '/images/parterowy3/sytuacja.jpg',
    kulaUrl:
      'https://kuula.co/share/hxTT1/collection/7DJXn?logo=0&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&enablejs=1&fid=0f44&priority=1',
  },
  {
    slug: 'parterowy-5',
    name: 'Parterowy 5',
    price: 599000,
    hasGarage: false,
    available: true,
    description:
      'Wyjątkowy dom dwurodzinny z dwoma osobnymi wejściami, kuchniami i salonami na wspólnej działce. Idealne rozwiązanie dla dwóch rodzin chcących mieszkać blisko siebie.',
    zones:
      'Każda część domu ma wyraźnie wydzieloną strefę reprezentacyjną i nocną, zapewniając niezależność i komfort obu rodzinom.',
    general: {
      buildingArea: '172.00 m²',
      usableArea: '139.00 m²',
      volume: '590.00 m³',
      roofAngle: '2°',
      rooms: 6,
      type: 'murowany',
    },
    plotDimensions: { width: '22.00 m', length: '28.00 m' },
    rooms: [
      { name: 'Pokój dzienny (lokal 1)', area: '28.00 m²' },
      { name: 'Kuchnia (lokal 1)', area: '10.00 m²' },
      { name: 'Sypialnia I (lokal 1)', area: '12.00 m²' },
      { name: 'Sypialnia II (lokal 1)', area: '10.00 m²' },
      { name: 'Łazienka (lokal 1)', area: '4.50 m²' },
      { name: 'Pokój dzienny (lokal 2)', area: '28.00 m²' },
      { name: 'Kuchnia (lokal 2)', area: '10.00 m²' },
      { name: 'Sypialnia I (lokal 2)', area: '12.00 m²' },
      { name: 'Sypialnia II (lokal 2)', area: '10.00 m²' },
      { name: 'Łazienka (lokal 2)', area: '4.50 m²' },
    ],
    construction: [
      { name: 'Fundamenty', value: 'płyta fundamentowa' },
      { name: 'Ściany', value: 'pustak ceramiczny' },
      { name: 'Strop', value: 'drewniany' },
      {
        name: 'Dach',
        value:
          'izolacja pozioma polistyren ekstrudowany EPS oraz membrana dachowa',
      },
      { name: 'Okna', value: 'PCV trzyszybowe' },
      { name: 'Stolarka drzwiowa', value: 'drzwi zewnętrzne x2' },
      { name: 'Tynki', value: 'gipsowe' },
      { name: 'Posadzki', value: 'betonowe' },
      {
        name: 'Instalacje',
        value: 'ogrzewanie podłogowe, instalacje elektryczne i wod.-kan.',
      },
      { name: 'Elewacja', value: 'styropian i tynk silikonowy' },
    ],
    images: [
      '/images/parterowy5/1.jpg',
      '/images/parterowy5/2.jpg',
      '/images/parterowy5/3.jpg',
      '/images/parterowy5/4.jpg',
    ],
    floorPlan: '/images/parterowy5/rzut.jpg',
    sitePlan: '/images/parterowy5/sytuacja.jpg',
    kulaUrl:
      'https://kuula.co/share/hxTT1/collection/7DJXn?logo=0&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&enablejs=1&fid=0f44&priority=1',
  },
  {
    slug: 'parterowy-6',
    name: 'Parterowy 6',
    price: 515000,
    hasGarage: false,
    available: true,
    description:
      'Klasyczny układ z trzema sypialniami i przestronnym salonem. Jeden z najpopularniejszych projektów w ofercie. Duży taras i wyjście bezpośrednio do ogrodu.',
    zones:
      'Reprezentacyjna oraz nocna są wyraźnie wydzielone, co zapewnia domownikom wygodę i komfort użytkowania.',
    general: {
      buildingArea: '130.00 m²',
      usableArea: '105.75 m²',
      volume: '455.00 m³',
      roofAngle: '2°',
      rooms: 3,
      type: 'murowany',
    },
    plotDimensions: { width: '19.00 m', length: '25.00 m' },
    rooms: [
      { name: 'Pokój dzienny', area: '30.00 m²' },
      { name: 'Kuchnia', area: '10.00 m²' },
      { name: 'Sypialnia I', area: '13.00 m²' },
      { name: 'Sypialnia II', area: '11.00 m²' },
      { name: 'Sypialnia III', area: '9.00 m²' },
      { name: 'Łazienka', area: '4.75 m²' },
      { name: 'WC', area: '2.00 m²' },
      { name: 'Komunikacja', area: '9.00 m²' },
      { name: 'Kotłownia', area: '5.00 m²' },
    ],
    construction: [
      { name: 'Fundamenty', value: 'płyta fundamentowa' },
      { name: 'Ściany', value: 'pustak ceramiczny' },
      { name: 'Strop', value: 'drewniany' },
      {
        name: 'Dach',
        value:
          'izolacja pozioma polistyren ekstrudowany EPS oraz membrana dachowa',
      },
      { name: 'Okna', value: 'PCV trzyszybowe' },
      { name: 'Stolarka drzwiowa', value: 'drzwi zewnętrzne' },
      { name: 'Tynki', value: 'gipsowe' },
      { name: 'Posadzki', value: 'betonowe' },
      {
        name: 'Instalacje',
        value: 'ogrzewanie podłogowe, instalacje elektryczne i wod.-kan.',
      },
      { name: 'Elewacja', value: 'styropian i tynk silikonowy' },
    ],
    images: [
      '/images/parterowy6/1.jpg',
      '/images/parterowy6/2.jpg',
      '/images/parterowy6/3.jpg',
      '/images/parterowy6/4.jpg',
    ],
    floorPlan: '/images/parterowy6/rzut.jpg',
    sitePlan: '/images/parterowy6/sytuacja.jpg',
    kulaUrl:
      'https://kuula.co/share/hxTT1/collection/7DJXn?logo=0&info=0&fs=1&vr=1&sd=1&initload=0&thumbs=1&enablejs=1&fid=0f44&priority=1',
  },
]

export type Project = (typeof projects)[0]

export const withGarage = projects.filter((p) => p.hasGarage)
export const withoutGarage = projects.filter((p) => !p.hasGarage)
